<?php 
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
wp_nonce_field( 'save_sip_advanced_email_notification_meta_box_free', 'sip_advanced_email_notification_meta_box_nonce' );
?><div class="card ">
<div class="card-header">
   <h5 class="card-title">Emails</h5>
</div>
<div class="card-body">
   <div id="email-chain-container" class="form-field sip_a_e_n_wc_email_chain_field">
      <div id="email_chain">
         <div id="tbody_email_chain" class="mg-t-20">
            <?php
               
               $chain = sip_aenwc_get_chain_of_post_id_free ( $post->ID );
if (!empty($chain)) {

			?>

	<input id="chain_row_0_BEFORE" name="chain[0][BEFORE]" class="requried-entry input-text required-entry custgroup" value="1" type="hidden">

	<div id="0" class="email_chain_box_email_preview">
		<div class="email-formpart-box">

				<div class="card tx-black bg-light">
                     <div class="card-header tx-semibold"> <?php _e('Send After (Pro):', 'sip-advanced-email-notifications-for-wc-free' ); ?> </div>
                     <div class="card-body">
                        <input type="number" min="0" class="requried-entry input-text required-entry custgroup disabled" placeholder="0" style="width: 60px;" disabled> <?php _e('Days', 'sip-advanced-email-notifications-for-wc-free' ); ?>
                        
						<select class="requried-entry input-text required-entry custgroup">
                           <?php for( $i = 0; $i < 24; $i ++ ) { 
							   		$selected = "";
									   if($i == 0){
										$selected = "selected='selected'";
									   }
							   ?>
								<option disabled <?php echo $selected; ?>> <?php echo $i; ?></option>
                           <?php } ?>
                        </select>
                        <?php _e('Hours', 'sip-advanced-email-notifications-for-wc-free' ); ?>

                        <select class="requried-entry input-text required-entry custgroup">
                           <?php for( $i = 0; $i <= 59; $i ++ ) {
							 	$selected = "";
								 if($i == 0){
								  $selected = "selected='selected'";
								 }  
							   ?>
                           		<option disabled <?php echo $selected; ?>> <?php echo $i; ?></option>
                           <?php } ?>
                        </select>
                        <?php _e('Minutes', 'sip-advanced-email-notifications-for-wc-free' ); ?>
						
                     </div>
				</div>


			<div class="card tx-black bg-light mg-b-20 mg-t-20">
				<div id="email_chain_box_0_">
					<div class="card-body">
						<div class="form-group mt-2">
							<label for="chain_0_subject">Email Subject*</label>
							<input type="text" placeholder="Email Subject" name="chain[0][subject]" id="chain_0_subject" class="mail-subject form-control" value="<?php echo esc_html($chain['subject']); ?>">
						</div>
						<?php
							$content = $chain['content'];
						?>
						
						<textarea id="summernote_0_content"  class="form-control summernote" name="chain[0][content]"><?php echo $content;?></textarea>
					</div>
				</div>
			</div>
			<div class="card tx-black bg-light mg-b-20 mg-t-20">
				<div class="card-header tx-semibold"> <?php _e('Send copy to email', 'sip-advanced-email-notifications-for-wc-free' ); ?></div>
				<div class="card-body clear">
					<div class="row">
						

						<div class="col-md-4 form-group form-field sip_a_e_n_wc_bcc_field ">
							<label for="sip_a_e_n_wc_bcc" ><?php _e('Send copy to email (Pro)', 'sip-advanced-email-notifications-for-wc-free' ); ?></label>
							<a tabindex="0" class="formhelpp" role="button" data-toggle="tooltip"  data-original-title="<?php _e('These addresses will be added to the BCC: fields of the emails generated by the rule Separate e-mails by spaces, commas, or semicolons.', 'sip-advanced-email-notifications-for-wc-free' ); ?>"> <i class="ion-ios-help-circle"></i></a> 
							<input type="text" placeholder="" id="sip_a_e_n_wc_bcc" name="" value="" class="short form-control disabled" disabled multiple />
						</div>


						<div class="col-md-4 form-group form-field sip_a_e_n_wc_to_customer_field ">
							<div class="form-group form-field sip_a_e_n_wc_to_customer_field ">
								<label for="sip_a_e_n_wc_to_customer" ><?php _e('Send email to customer', 'sip-advanced-email-notifications-for-wc-free' ); ?></label>
								<a tabindex="0" class="formhelpp" role="button" data-toggle="tooltip"  data-original-title="<?php _e('If "No" is selected, email will be sent to recipients specified in the "Send copy to email" field only', 'sip-advanced-email-notifications-for-wc-free' ); ?>"> <i class="ion-ios-help-circle"></i> </a>
								<select style="" class="select short custom-select " name="chain[0][TO_CUSTOMER]" id="sip_a_e_n_wc_to_customer">
									<option value="yes" <?php echo ( $chain['to_customer'] == 'yes')? 'selected="selected"':''; ?> ><?php _e('Yes', 'sip-advanced-email-notifications-for-wc-free' ); ?></option>
									<option value="no" <?php echo ( $chain['to_customer'] == 'no')? 'selected="selected"':''; ?>><?php _e('No', 'sip-advanced-email-notifications-for-wc-free' ); ?></option>
								</select>
							</div>
						</div>

						<div class="col-md-4 form-group mt-4">
							<input type="hidden" id="chain_0_is_new" name="chain[0][is_new]" value="0" />
							<input type="hidden" id="chain_0_is_new" name="chain[0][email_chain_id]" value="<?php echo $chain["id"]; ?>" />
							
							<button id="id_chain_preview_email_0" title="<?php _e('Preview Email' , 'sip-advanced-email-notifications-for-wc-free') ?>" type="button" class="scalable preview-email btn btn-danger">
							<?php _e('Preview Email' , 'sip-advanced-email-notifications-for-wc-free')?>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>



<?php
	}else{ 
?>

				<input id="chain_row_0_BEFORE" name="chain[0][BEFORE]" class="requried-entry input-text required-entry custgroup" value="1" type="hidden">
				<input type="hidden" id="chain_0_is_new" name="chain[0][is_new]" value="1" />
				<input type="hidden" id="chain_0_is_new" name="chain[0][email_chain_id]" value="" />
				<div id="0">
					<div class="email-formpart-box">

					<div class="card tx-black bg-light">
						<div class="card-header tx-semibold"> <?php _e('Send After (Pro):', 'sip-advanced-email-notifications-for-wc-free' ); ?> </div>
						<div class="card-body">
							<input type="number" min="0" class="requried-entry input-text required-entry custgroup disabled" placeholder="0" style="width: 60px;" disabled> <?php _e('Days', 'sip-advanced-email-notifications-for-wc-free' ); ?>
							
							<select class="requried-entry input-text required-entry custgroup">
							<?php for( $i = 0; $i < 24; $i ++ ) { 
										$selected = "";
										if($i == 0){
											$selected = "selected='selected'";
										}
								?>
									<option disabled <?php echo $selected; ?>> <?php echo $i; ?></option>
							<?php } ?>
							</select>
							<?php _e('Hours', 'sip-advanced-email-notifications-for-wc-free' ); ?>

							<select class="requried-entry input-text required-entry custgroup">
							<?php for( $i = 0; $i <= 59; $i ++ ) {
									$selected = "";
									if($i == 0){
									$selected = "selected='selected'";
									}  
								?>
									<option disabled <?php echo $selected; ?>> <?php echo $i; ?></option>
							<?php } ?>
							</select>
							<?php _e('Minutes', 'sip-advanced-email-notifications-for-wc-free' ); ?>
							
						</div>
					</div>
					
					<div class="card tx-black bg-light mg-b-20 mg-t-20">
						<div id="email_chain_box_0_">
							<div class="card-body">
								<div class="form-group mt-2">
								<label for="chain_0_subject">Email Subject*</label><input type="text" placeholder="Email Subject" name="chain[0][subject]" id="chain_0_subject" class="mail-subject form-control" value="">
								</div>
								
								<textarea id="summernote_0_content"  class="form-control summernote" name="chain[0][content]"></textarea>
							</div>
						</div>
					</div>
					<div class="card tx-black bg-light mg-b-20 mg-t-20">
						<div class="card-header tx-semibold"> <?php _e('Send copy to email', 'sip-advanced-email-notifications-for-wc-free' ); ?></div>
						<div class="card-body clear">
							<div class="row">
								
								<div class="col-md-6">
                                    <div class="form-group form-field sip_a_e_n_wc_bcc_field ">
                                       <label for="sip_a_e_n_wc_bcc" ><?php _e('Send copy to email (Pro)', 'sip-advanced-email-notifications-for-wc-free' ); ?> </label>
                                       <a tabindex="0" class="formhelpp" role="button" data-toggle="tooltip"  data-original-title="<?php _e('These addresses will be added to the BCC: fields of the emails generated by the rule Separate e-mails by spaces, commas, or semicolons.', 'sip-advanced-email-notifications-for-wc-free' ); ?>"> <i class="ion-ios-help-circle"></i></a> 
                                       <input type="text" placeholder="" id="sip_a_e_n_wc_bcc" class="short form-control disabled" disabled />
                                    </div>
                                 </div>

								<div class="col-md-6">
									<div class="form-group form-field sip_a_e_n_wc_to_customer_field ">
										<label for="sip_a_e_n_wc_to_customer" ><?php _e('Send email to customer', 'sip-advanced-email-notifications-for-wc-free' ); ?>   </label>
										<a tabindex="0" class="formhelpp" role="button" data-toggle="tooltip"  data-original-title="<?php _e('If "No" is selected, email will be sent to recipients specified in the "Send copy to email" field only', 'sip-advanced-email-notifications-for-wc-free' ); ?>"> <i class="ion-ios-help-circle"></i> </a>
										<select style="" class="select short custom-select " name="chain[0][TO_CUSTOMER]" id="sip_a_e_n_wc_to_customer">
											<option value="yes" selected="selected"><?php _e('Yes', 'sip-advanced-email-notifications-for-wc-free' ); ?></option>
											<option value="no"><?php _e('No', 'sip-advanced-email-notifications-for-wc-free' ); ?></option>
										</select>
									</div>
								</div>
							</div>
						</div>
					</div>
					</div>
				</div>
<?php 
	}
?>
               </div>
            </div>
         </div>
      </div>
   </div>